"""Add Riot summoner fields to user model

Revision ID: 9692d1cba511
Revises: 8399c0d544c5
Create Date: 2025-06-12 11:28:36.449338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9692d1cba511'
down_revision = '8399c0d544c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.BigInteger(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('discord_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lol_summoner_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('lol_summoner_tag', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('puuid', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['puuid'])
        batch_op.drop_column('username')
        batch_op.drop_column('email')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('puuid')
        batch_op.drop_column('lol_summoner_tag')
        batch_op.drop_column('lol_summoner_name')
        batch_op.drop_column('discord_name')
        batch_op.drop_column('discord_id')

    # ### end Alembic commands ###
