"""Add collaborative writing workflow fields to NewsArticle

Revision ID: dfca19773e33
Revises: 8a7a270dce64
Create Date: 2025-06-29 13:25:28.292528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfca19773e33'
down_revision = '8a7a270dce64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_contribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('enhanced_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('workflow_phase', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('workflow_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_article', schema=None) as batch_op:
        batch_op.drop_column('workflow_metadata')
        batch_op.drop_column('workflow_phase')
        batch_op.drop_column('enhanced_content')
        batch_op.drop_column('user_contribution')

    op.create_table('user',
    sa.Column('discord_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('discord_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lol_summoner_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('lol_summoner_tag', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('puuid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('discord_id', name=op.f('user_pkey')),
    sa.UniqueConstraint('puuid', name=op.f('user_puuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
